{"uid":"2462957154c5055e","name":"test_dagbag_import_errors","fullName":"test.test_dags_general.TestDagsGeneral#test_dagbag_import_errors","historyId":"166f6681a38c1023b4ff492def40bf75","time":{"start":1744710204125,"stop":1744710204126,"duration":1},"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","descriptionHtml":"<pre><code>    Test that there are no DAG import errors.\n    \n    Import errors usually indicate syntax errors or missing dependencies\n    that prevent the DAG from being properly loaded.\n</code></pre>\n","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7f9504774280>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7f94fb887490>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7f9504774280>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7f9504774280>.import_errors\n\ntest/test_dags_general.py:88: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"dagbag","time":{"start":1744710204108,"stop":1744710204124,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dagbag","time":{"start":1744710204450,"stop":1744710204451,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7f9504774280>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7f94fb887490>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7f9504774280>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7f9504774280>.import_errors\n\ntest/test_dags_general.py:88: AssertionError","steps":[],"attachments":[{"uid":"b2dc6dff6c0d0238","name":"log","source":"b2dc6dff6c0d0238.txt","type":"text/plain","size":1942},{"uid":"40be04c5eb5c16b5","name":"stdout","source":"40be04c5eb5c16b5.txt","type":"text/plain","size":1960}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"parentSuite","value":"test"},{"name":"suite","value":"test_dags_general"},{"name":"subSuite","value":"TestDagsGeneral"},{"name":"host","value":"fv-az1940-600"},{"name":"thread","value":"3940-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.test_dags_general"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"2462957154c5055e.json","parameterValues":[]}