{"uid":"59966bbc8e0fb643","name":"test_file_imports[dags/dbt_simple_task_group.py]","fullName":"test.test_dags_general#test_file_imports","historyId":"e936d9b66761de10c5efd8d1b02f7a56","time":{"start":1744710204426,"stop":1744710204427,"duration":1},"description":"\n    Test for import errors on a file.\n    \n    This test checks each DAG file for import errors and provides detailed\n    error messages if problems are found.\n    ","descriptionHtml":"<pre><code>Test for import errors on a file.\n\nThis test checks each DAG file for import errors and provides detailed\nerror messages if problems are found.\n</code></pre>\n","status":"broken","statusMessage":"Exception: dags/dbt_simple_task_group.py failed to import with message \n Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\n    project_config.validate_project()\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json","statusTrace":"rel_path = 'dags/dbt_simple_task_group.py'\nrv = 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos...{name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json'\n\n    @pytest.mark.parametrize(\n        \"rel_path,rv\", get_import_errors(), ids=[x[0] for x in get_import_errors()]\n    )\n    def test_file_imports(rel_path, rv):\n        \"\"\"\n        Test for import errors on a file.\n    \n        This test checks each DAG file for import errors and provides detailed\n        error messages if problems are found.\n        \"\"\"\n        if rel_path and rv:\n>           raise Exception(f\"{rel_path} failed to import with message \\n {rv}\")\nE           Exception: dags/dbt_simple_task_group.py failed to import with message \nE            Traceback (most recent call last):\nE             File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\nE               project_config.validate_project()\nE             File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\nE               raise CosmosValueError(f\"Could not find {name} at {path}\")\nE           cosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\n\ntest/test_dags_general.py:180: Exception","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"test"},{"name":"suite","value":"test_dags_general"},{"name":"host","value":"fv-az1940-600"},{"name":"thread","value":"3940-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.test_dags_general"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"rel_path","value":"'dags/dbt_simple_task_group.py'"},{"name":"rv","value":"'Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\n    project_config.validate_project()\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"59966bbc8e0fb643.json","parameterValues":["'dags/dbt_simple_task_group.py'","'Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\n    project_config.validate_project()\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json'"]}