{"uid":"5d4cf2c5766bc72a","name":"test_dagbag_import_errors","fullName":"test_dags_general.TestDagsGeneral#test_dagbag_import_errors","historyId":"a2c30e60bd3adbfb3084f7c4abb839ff","time":{"start":1744704452667,"stop":1744704452667,"duration":0},"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","descriptionHtml":"<pre><code>    Test that there are no DAG import errors.\n    \n    Import errors usually indicate syntax errors or missing dependencies\n    that prevent the DAG from being properly loaded.\n</code></pre>\n","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7fd3625aca30>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>.import_errors\n\ntest_dags_general.py:88: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":false,"beforeStages":[{"name":"dagbag","time":{"start":1744704452650,"stop":1744704452666,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7fd3625aca30>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bfee0>.import_errors\n\ntest_dags_general.py:88: AssertionError","steps":[],"attachments":[{"uid":"8042797167e47d48","name":"log","source":"8042797167e47d48.txt","type":"text/plain","size":7771}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"suite","value":"test_dags_general"},{"name":"subSuite","value":"TestDagsGeneral"},{"name":"host","value":"fv-az1914-625"},{"name":"thread","value":"3889-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_dags_general"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e37d43f7ccfc8979","status":"failed","statusDetails":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>.import_errors","time":{"start":1744704452643,"stop":1744704452643,"duration":0}},{"uid":"244f7225076801fa","status":"failed","statusDetails":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd362488730>.import_errors","time":{"start":1744704452617,"stop":1744704452618,"duration":1}},{"uid":"d24470b7a55610bc","status":"failed","statusDetails":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd36264d550>.import_errors","time":{"start":1744704452431,"stop":1744704452432,"duration":1}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5d4cf2c5766bc72a.json","parameterValues":[]}